// Interface automatically generated by schemas-to-ts

export interface ProductCategory {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    name: string;
    slug?: string;
    description?: string;
  };
}
export interface ProductCategory_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  slug?: string;
  description?: string;
}

export interface ProductCategory_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  slug?: string;
  description?: string;
}

export interface ProductCategory_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  slug?: string;
  description?: string;
}
