// Interface automatically generated by schemas-to-ts

export interface EcoData {
  name: string;
  value: any;
}
export interface EcoData_Plain {
  name: string;
  value: any;
}

export interface EcoData_NoRelations {
  name: string;
  value: any;
}
