// Interface automatically generated by schemas-to-ts

export interface ProductSpecification {
  name: string;
  value: any;
}
export interface ProductSpecification_Plain {
  name: string;
  value: any;
}

export interface ProductSpecification_NoRelations {
  name: string;
  value: any;
}
